// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskNote.Models;

namespace TaskNote.Migrations
{
    [DbContext(typeof(TaskNoteContext))]
    partial class TaskNoteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskNote.Models.Contenedor", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PizarraId1");

                    b.Property<string>("nombre");

                    b.HasKey("ID");

                    b.HasIndex("PizarraId1");

                    b.ToTable("Contenedors");
                });

            modelBuilder.Entity("TaskNote.Models.Estilo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PizarraId1");

                    b.Property<string>("fondo");

                    b.Property<string>("font");

                    b.Property<string>("theme");

                    b.HasKey("ID");

                    b.HasIndex("PizarraId1");

                    b.ToTable("Estilos");
                });

            modelBuilder.Entity("TaskNote.Models.Pizarra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("tipoPizarra");

                    b.HasKey("Id");

                    b.ToTable("Pizarras");
                });

            modelBuilder.Entity("TaskNote.Models.Planner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Planners");
                });

            modelBuilder.Entity("TaskNote.Models.Tarjeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContenedorID");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("comentarios");

                    b.Property<int>("estado");

                    b.Property<Guid?>("estiloID");

                    b.Property<DateTime>("fechaFin");

                    b.Property<DateTime>("fechaInicio");

                    b.Property<string>("titulo");

                    b.HasKey("Id");

                    b.HasIndex("ContenedorID");

                    b.HasIndex("estiloID");

                    b.ToTable("Tarjetas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Tarjeta");
                });

            modelBuilder.Entity("TaskNote.Models.Usuario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PizarraId1");

                    b.Property<Guid?>("PlannerId");

                    b.Property<string>("contrasenia");

                    b.Property<string>("email");

                    b.Property<int>("idUsuario");

                    b.Property<DateTime>("nacimiento");

                    b.Property<string>("nombreApellido");

                    b.Property<string>("nombreUsuario");

                    b.HasKey("ID");

                    b.HasIndex("PizarraId1");

                    b.HasIndex("PlannerId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TaskNote.Models.Educacion", b =>
                {
                    b.HasBaseType("TaskNote.Models.Tarjeta");

                    b.Property<Guid?>("asignadoID");

                    b.Property<string>("aula");

                    b.Property<string>("establecimiento");

                    b.HasIndex("asignadoID");

                    b.HasDiscriminator().HasValue("Educacion");
                });

            modelBuilder.Entity("TaskNote.Models.Empresa", b =>
                {
                    b.HasBaseType("TaskNote.Models.Tarjeta");

                    b.Property<Guid?>("asignadoID")
                        .HasColumnName("Empresa_asignadoID");

                    b.Property<string>("centroDeCostos");

                    b.Property<string>("empresa");

                    b.HasIndex("asignadoID");

                    b.HasDiscriminator().HasValue("Empresa");
                });

            modelBuilder.Entity("TaskNote.Models.Personal", b =>
                {
                    b.HasBaseType("TaskNote.Models.Tarjeta");

                    b.HasDiscriminator().HasValue("Personal");
                });

            modelBuilder.Entity("TaskNote.Models.Contenedor", b =>
                {
                    b.HasOne("TaskNote.Models.Pizarra", "Pizarra")
                        .WithMany("contenedor")
                        .HasForeignKey("PizarraId1");
                });

            modelBuilder.Entity("TaskNote.Models.Estilo", b =>
                {
                    b.HasOne("TaskNote.Models.Pizarra", "Pizarra")
                        .WithMany("estilos")
                        .HasForeignKey("PizarraId1");
                });

            modelBuilder.Entity("TaskNote.Models.Tarjeta", b =>
                {
                    b.HasOne("TaskNote.Models.Contenedor")
                        .WithMany("tarjetas")
                        .HasForeignKey("ContenedorID");

                    b.HasOne("TaskNote.Models.Estilo", "estilo")
                        .WithMany()
                        .HasForeignKey("estiloID");
                });

            modelBuilder.Entity("TaskNote.Models.Usuario", b =>
                {
                    b.HasOne("TaskNote.Models.Pizarra", "Pizarra")
                        .WithMany("usuario")
                        .HasForeignKey("PizarraId1");

                    b.HasOne("TaskNote.Models.Planner")
                        .WithMany("usuario")
                        .HasForeignKey("PlannerId");
                });

            modelBuilder.Entity("TaskNote.Models.Educacion", b =>
                {
                    b.HasOne("TaskNote.Models.Usuario", "asignado")
                        .WithMany()
                        .HasForeignKey("asignadoID");
                });

            modelBuilder.Entity("TaskNote.Models.Empresa", b =>
                {
                    b.HasOne("TaskNote.Models.Usuario", "asignado")
                        .WithMany()
                        .HasForeignKey("asignadoID");
                });
#pragma warning restore 612, 618
        }
    }
}
